package HTTP::MobileAgent::Flash::DoCoMoFlashMap;
# -------------------------------------------------------------------------
# This file is autogenerated by ./make_map.pl
# in HTTP-MobileAgent-Flash distribution
# -------------------------------------------------------------------------
use strict;
use warnings;

require Exporter;
use base qw(Exporter);
use vars qw(@EXPORT_OK $FLASH_MAP);
@EXPORT_OK = qw($FLASH_MAP);


BEGIN {
    if ($ENV{DOCOMO_FLASH_MAP}) {
        eval q{
            require YAML::Syck;
            $FLASH_MAP = YAML::Syck::LoadFile($ENV{DOCOMO_FLASH_MAP});
        };
        if ($@) {
            eval q{
                require YAML;
                $FLASH_MAP = YAML::LoadFile($ENV{DOCOMO_FLASH_MAP});
            };
        }
        warn "using normal hash map: $@" if $@;
    }
}

$FLASH_MAP ||= {
  'N506IS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '400',
    'height' => '295'
  },
  'F883I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '256'
  },
  'F902IS' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'SH702IS' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '240'
  },
  'D903ITV' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '320'
  },
  'N900I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '1024',
    'height' => '269'
  },
  'SO903ITV' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '368'
  },
  'P702I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'D701I' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'SO703I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '368'
  },
  'P903I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'SH505I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '200',
    'height' => '252'
  },
  'N703ID' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'P900I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '1024',
    'height' => '266'
  },
  'SA800I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '252'
  },
  'D851IWM' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '320'
  },
  'P900IV' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '1024',
    'height' => '266'
  },
  'M702IG' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '600',
    'height' => '267'
  },
  'P851I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'P901I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'F900IT' => {
    'width' => '230',
    'version' => '1.0',
    'max_file_size' => '1000',
    'height' => '240'
  },
  'D505I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '200',
    'height' => '320'
  },
  'N601I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'D702I' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'P505IS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '404',
    'height' => '266'
  },
  'P902I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'SO902IWP' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '256'
  },
  'D901IS' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'N505I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '200',
    'height' => '270'
  },
  'SO903I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '368'
  },
  'N506I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '400',
    'height' => '295'
  },
  'P904I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '350'
  },
  'SH703I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '240'
  },
  'D800IDS' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'N901IS' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'SA702I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '252'
  },
  'SH900I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '1000',
    'height' => '252'
  },
  'F903I' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '240'
  },
  'F901IC' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'SO506I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '400',
    'height' => '256'
  },
  'D703I' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '240'
  },
  'D702IF' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'SH902I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '240'
  },
  'F700I' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'N506ISII' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '400',
    'height' => '295'
  },
  'N902IL' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'N901IC' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'N900IG' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '1024',
    'height' => '269'
  },
  'SH506IC' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '300',
    'height' => '252'
  },
  'P506ICII' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '404',
    'height' => '266'
  },
  'F702ID' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'SH904I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '320'
  },
  'P702ID' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'N702ID' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'P703I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'SA700IS' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '252'
  },
  'SH901IC' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '2048',
    'height' => '252'
  },
  'P903IX' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'P901ITV' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'SH700IS' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '252'
  },
  'SO506IS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '400',
    'height' => '256'
  },
  'F506I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '300',
    'height' => '268'
  },
  'D702IBCL' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'SH901IS' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '252'
  },
  'N701I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'SO505IS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '400',
    'height' => '256'
  },
  'N703I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'F700IS' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'N903I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'N700I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'D902IS' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '320'
  },
  'D506I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '300',
    'height' => '270'
  },
  'D902I' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '320'
  },
  'M702IS' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '600',
    'height' => '267'
  },
  'D701IWM' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'SH902IS' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '240'
  },
  'D901I' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'N505IS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '400',
    'height' => '270'
  },
  'F900IC' => {
    'width' => '230',
    'version' => '1.0',
    'max_file_size' => '1000',
    'height' => '240'
  },
  'SO702I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '256'
  },
  'D505IS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '300',
    'height' => '270'
  },
  'N900IS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '1024',
    'height' => '269'
  },
  'SH700I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '252'
  },
  'P701ID' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'F902I' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'P505I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '256',
    'height' => '266'
  },
  'F903IBSC' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '240'
  },
  'SO506IC' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '400',
    'height' => '256'
  },
  'N904I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '352'
  },
  'P903ITV' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '350'
  },
  'SH902ISL' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '240'
  },
  'N902I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'SO704I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '368'
  },
  'D903I' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '320'
  },
  'D900I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '1024',
    'height' => '270'
  },
  'P901IS' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'F703I' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '240'
  },
  'F900I' => {
    'width' => '230',
    'version' => '1.0',
    'max_file_size' => '1000',
    'height' => '240'
  },
  'P902IS' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'F901IS' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '240'
  },
  'F505IGPS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '300',
    'height' => '268'
  },
  'SO902I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '256'
  },
  'SH903I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '320'
  },
  'N902IS' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'N900IL' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '1024',
    'height' => '269'
  },
  'SH903ITV' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '320'
  },
  'N702IS' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'P506IC' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '404',
    'height' => '266'
  },
  'P700I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '270'
  },
  'SH702ID' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '240'
  },
  'F505I' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '300',
    'height' => '268'
  },
  'N701IECO' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'F903IX' => {
    'width' => '230',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '240'
  },
  'N902IX' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '270'
  },
  'F904I' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2048',
    'height' => '432'
  },
  'F882IES' => {
    'width' => '240',
    'version' => '1.1',
    'max_file_size' => '2000',
    'height' => '256'
  },
  'SH505IS' => {
    'width' => '240',
    'version' => '1.0',
    'max_file_size' => '300',
    'height' => '252'
  }
}
;

1;
