package HTTP::MobileAgent::Flash::EZWebFlashMap;
# -------------------------------------------------------------------------
# This file is autogenerated by make_map_flash_lite.pl
# in HTTP::MobileAgent::Flash distribution.
#
# make_map_flash_lite.pl --carrier=ezweb --output=pm
# -------------------------------------------------------------------------

use strict;
use warnings;

require Exporter;
use base qw(Exporter);
our @EXPORT_OK = qw($FLASH_MAP);
our $FLASH_MAP;

BEGIN {
    if ($ENV{EZWEB_FLASH_MAP}) {
        eval q{
            require YAML::Syck;
            $FLASH_MAP = YAML::Syck::LoadFile($ENV{EZWEB_FLASH_MAP});
        };
        if ($@) {
            eval q{
                require YAML;
                $FLASH_MAP = YAML::LoadFile($ENV{EZWEB_FLASH_MAP});
            };
        }
        warn "using normal hash map: $@" if $@;
    }
}

$FLASH_MAP ||= {
};

1;